# Generated by Django 5.0.6 on 2024-06-04 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('prof_standart', '0002_delete_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalStandart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('created', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('found_by', models.CharField(max_length=500)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profstandarts', to='api.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('profstandart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_titles', to='prof_standart.professionalstandart')),
            ],
        ),
    ]
