# Generated by Django 5.0.6 on 2024-06-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof_standart', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobtitle',
            table='jobtitle',
        ),
        migrations.AlterModelTable(
            name='professionalstandart',
            table='professionalstandart',
        ),
    ]
