# Generated by Django 5.0.6 on 2024-06-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_standart', '0004_alter_jobtitle_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalstandart',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
