# Generated by Django 5.0.6 on 2024-06-05 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dataset_table'),
        ('labor_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_data', models.CharField(max_length=10000)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='api.dataset')),
            ],
            options={
                'db_table': 'cluster',
            },
        ),
    ]
